Complete Bangla dictionary probably ported from avrodict, provided by Sarim Khan (#15)
* Fixing AttributeError: 'NoneType' object has no attribute 'decode'

* Setting up exception to almost all errors

* Adding Layout & Language Dictionary

* Removing unnecessary f.close() and adding Bangla language support

* Renaming get_dict_dir by get_language_name and making another get_dict_dir function

* Supporting multi-languages in get_suggestions function

* Any phrase can be passed as param

* Re-commenting

* Applying compatibility with Rofi, a drop-in replacement of dmenu

* Unwanted f.close() removed

* Adding main() function to avoid unwanted function not found errors

* Adding main() function to avoid unwanted function not found errors

* Renaming Language_Layout.txt to language_layout.py

* Moving get_language_name and get_dict_dir functions from TextSuggest.py to language_layout.py

* Renaming language_layout.py to languages.py

* This file contain a function get_font_name which will determine the font name depending on language

* Fixing ImportError: No module named 'language_layout'

* Changing Bangla font to SolaimanLipi

* Changing probhat to bd(probhat)

* Changing bd(probhat) to bd

* Fixing NameError: name 'font' is not defined

* Fixing spelling mistakes

* Fix font error

* Implementing ~/.TextSuggest_Dictionaries directory

* Implementing ~/.TextSuggest_Dictionaries directory

* Adding words

* Changing directory tree, deleting Language_Layout.txt

* Changing directory tree, deleting Language_Layout.txt

* Changing directory to ~/.config/textsuggest/

* Declaring variable for every file in textsuggest dir

* Adding some languages with fonts

* Re-addning automatic font

* Fixing bug

* Fixing font bug

* Update Custom_Words.txt

* Update history.txt

* Delete Custom_Words.txt

* Delete history.txt

* Adding Custom_Words.txt history.txt

* Adding more to the list

* Error solved

* Silently moved ~/.Custom_Words.txt (if found) to its new location

* Complete Bangla dictionary probably ported from avrodict, provided by Sarim Khan